// @ts-check
// Docs sidebar. Mostly autogenerated from the docs/ folder structure,
// with an explicit ordering for the Getting Started flow.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'concepts',
    'start-with-itoss',        
    {
      type: 'category',
      label: 'Managed Technologies',
      items: [
        {
          type: 'category',
          label: 'Databases',
          items: [
            'managed-technologies/databases/hana',
            'managed-technologies/databases/microsoft-sql-server',
            'managed-technologies/databases/mysql',
            'managed-technologies/databases/oracle',
            'managed-technologies/databases/postgre-sql',
            'managed-technologies/databases/sybase',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft Windows Server',
          items: [
            'managed-technologies/microsoft-windows-server/managed-windows-server-tasks',
          ],
        },
        {
          type: 'category',
          label: 'SAP',
          items: [
            'managed-technologies/sap/sap-abap',
          ],
        },
      ],
    }/*,
    {
      type: 'category',
      label: 'Reference',
      items: [        
        {
          type: 'category',
          label: 'Monitor',
          items: [
            'reference/monitors/event-rules',
          ],
        }
      ],
    },*/
  ],
};

export default sidebars;
