// @ts-check
// Docs sidebar. Mostly autogenerated from the docs/ folder structure,
// with an explicit ordering for the Getting Started flow.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    'concepts',    
    'start-with-itoss',
    {
      type: 'category',
      label: 'For Support Users',
      link: {type: 'doc', id: 'for-support-users/intro'},
      items: [
        {
          type: 'category',
          label: 'Understanding the Managed Environment',
          items: [
            'for-support-users/understanding-the-managed-environment/managed-components',
            'for-support-users/understanding-the-managed-environment/companies-support-teams-and-contacts',
            'for-support-users/understanding-the-managed-environment/component-lifecycle-management',
          ],
        },
        {
          type: 'category',
          label: 'Operational Management',
          items: [
            'for-support-users/operational-management/managing-technology-with-itoss',
            'for-support-users/operational-management/operational-dashboard',
            'for-support-users/operational-management/notifications',
          ],
        },
        {
          type: 'category',
          label: 'Operational Views',
          items: [
            'for-support-users/operational-views/general-status-dashboard',
            'for-support-users/operational-views/component-dashboard',
            'for-support-users/operational-views/company-dashboard',
          ],
        },
        {
          type: 'category',
          label: 'Reporting and Historical Analysis',
          items: [
            'for-support-users/reporting-and-historical-analysis/reports',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Managed Technologies',
      items: [
        {
          type: 'category',
          label: 'Databases',
          items: [
            'managed-technologies/databases/hana',
            'managed-technologies/databases/microsoft-sql-server',
            'managed-technologies/databases/mysql',
            'managed-technologies/databases/oracle',
            'managed-technologies/databases/postgre-sql',
            'managed-technologies/databases/sybase',
          ],
        },
        {
          type: 'category',
          label: 'Microsoft Windows Server',
          items: [
            'managed-technologies/microsoft-windows-server/managed-windows-server-tasks',
          ],
        },
        {
          type: 'category',
          label: 'SAP',
          items: [
            'managed-technologies/sap/sap-abap',
          ],
        },
      ],
    }/*,
    {
      type: 'category',
      label: 'Reference',
      items: [        
        {
          type: 'category',
          label: 'Monitor',
          items: [
            'reference/monitors/event-rules',
          ],
        }
      ],
    },*/
  ],
};

export default sidebars;
